-- Notification System Database Schema
-- Clean, strict SQL, Postgres-compatible, Supabase-safe

-- 1. notification_users
-- Who is allowed to receive notifications
create table if not exists notification_users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text not null, -- Creator, Admin, Ops, Marketing
  email text,
  phone text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- 2. notification_types
-- Hard-coded registry of allowed notification events
create table if not exists notification_types (
  key text primary key, -- e.g. POSTER_GENERATED
  description text not null,
  created_at timestamp with time zone default now()
);

-- Seed notification types
insert into notification_types (key, description) values
('ADMIN_LOGIN', 'Admin logged into the system'),
('TEMPLATE_CREATED', 'Poster template created'),
('TEMPLATE_UPDATED', 'Poster template updated'),
('TEMPLATE_DELETED', 'Poster template deleted'),
('TEMPLATE_STATUS_CHANGED', 'Poster template enabled or disabled'),
('POSTER_GENERATED', 'Poster generated by user'),
('PAYMENT_SUCCESS', 'Payment completed successfully'),
('PAYMENT_FAILED', 'Payment failed'),
('POSTER_DOWNLOADED', 'Poster downloaded'),
('POSTER_REVIEW_SUBMITTED', 'User submitted poster review')
on conflict (key) do nothing;

-- 3. notification_user_settings
-- Who gets what. How. Or not at all.
create table if not exists notification_user_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references notification_users(id) on delete cascade,
  notification_type text not null references notification_types(key) on delete cascade,
  via_email boolean default true,
  via_sms boolean default false,
  enabled boolean default true,
  created_at timestamp with time zone default now(),
  unique (user_id, notification_type)
);

-- 4. notification_templates
-- Customizable message content per notification type
create table if not exists notification_templates (
  id uuid primary key default gen_random_uuid(),
  notification_type text not null references notification_types(key) on delete cascade,
  channel text not null check (channel in ('email', 'sms')),
  subject text, -- email only
  body text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique (notification_type, channel)
);

-- 5. notification_events
-- Every thing that happens lands here. Append-only. No edits.
create table if not exists notification_events (
  id uuid primary key default gen_random_uuid(),
  notification_type text not null references notification_types(key),
  actor_type text not null check (actor_type in ('admin', 'user', 'system')),
  actor_identifier text, -- admin email, user phone, or system name
  summary text not null,
  metadata jsonb not null default '{}',
  created_at timestamp with time zone default now()
);

-- 6. notification_deliveries
-- Tracks actual sending, not intentions
create table if not exists notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references notification_events(id) on delete cascade,
  user_id uuid not null references notification_users(id) on delete cascade,
  channel text not null check (channel in ('email', 'sms')),
  status text not null check (status in ('pending', 'sent', 'failed')),
  provider_response text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- 7. Indexes (Performance critical)
create index if not exists idx_notification_events_type on notification_events(notification_type);
create index if not exists idx_notification_events_created_at on notification_events(created_at);
create index if not exists idx_notification_deliveries_event on notification_deliveries(event_id);
create index if not exists idx_notification_deliveries_user on notification_deliveries(user_id);
create index if not exists idx_notification_deliveries_status on notification_deliveries(status);

-- 8. Seed default templates
-- Email templates
insert into notification_templates (notification_type, channel, subject, body) values
('ADMIN_LOGIN', 'email', 'Admin Login Alert', 'Admin {{email}} logged in at {{time}} from IP {{ip}}.'),
('TEMPLATE_CREATED', 'email', 'New Template Created', 'Template "{{template_name}}" ({{template_id}}) was created by {{actor_identifier}} at {{time}}.'),
('TEMPLATE_UPDATED', 'email', 'Template Updated', 'Template "{{template_name}}" was updated by {{actor_identifier}} at {{time}}.'),
('TEMPLATE_DELETED', 'email', 'Template Deleted', 'Template "{{template_name}}" was deleted by {{actor_identifier}} at {{time}}.'),
('TEMPLATE_STATUS_CHANGED', 'email', 'Template Status Changed', 'Template "{{template_name}}" status changed to {{status}} by {{actor_identifier}} at {{time}}.'),
('POSTER_GENERATED', 'email', 'Poster Generated', 'Poster "{{template_name}}" was generated by {{user_phone}} at {{time}}. View: {{poster_link}}'),
('PAYMENT_SUCCESS', 'email', 'Payment Received', 'Payment of KES {{amount}} received from {{phone}} ({{mpesa_code}}) for {{template_name}} at {{time}}.'),
('PAYMENT_FAILED', 'email', 'Payment Failed', 'Payment from {{phone}} failed at {{time}}. Reason: {{reason}}.'),
('POSTER_DOWNLOADED', 'email', 'Poster Downloaded', 'Poster {{poster_id}} ({{template_name}}) was downloaded by {{phone}} at {{time}}.'),
('POSTER_REVIEW_SUBMITTED', 'email', 'Feedback Received', 'Rating {{rating}}/5 from {{phone}} for {{template_name}}: "{{comment}}" at {{time}}.')
on conflict (notification_type, channel) do nothing;

-- SMS templates
insert into notification_templates (notification_type, channel, subject, body) values
('ADMIN_LOGIN', 'sms', null, 'Admin {{email}} logged in at {{time}}.'),
('TEMPLATE_CREATED', 'sms', null, 'Template {{template_name}} created.'),
('TEMPLATE_UPDATED', 'sms', null, 'Template {{template_name}} updated.'),
('TEMPLATE_DELETED', 'sms', null, 'Template {{template_name}} deleted.'),
('TEMPLATE_STATUS_CHANGED', 'sms', null, 'Template {{template_name}} status: {{status}}.'),
('POSTER_GENERATED', 'sms', null, 'Poster {{template_name}} generated by {{user_phone}}.'),
('PAYMENT_SUCCESS', 'sms', null, 'Payment KES {{amount}} from {{phone}} ({{mpesa_code}}).'),
('PAYMENT_FAILED', 'sms', null, 'Payment failed from {{phone}}.'),
('POSTER_DOWNLOADED', 'sms', null, 'Poster downloaded: {{template_name}}.'),
('POSTER_REVIEW_SUBMITTED', 'sms', null, 'Feedback: {{rating}}/5 from {{phone}}.')
on conflict (notification_type, channel) do nothing;

-- 9. Insert default admin user (customize as needed)
insert into notification_users (name, role, email, phone, is_active) values
('System Admin', 'Admin', 'admin@example.com', null, true)
on conflict do nothing;
